apiVersion: v1
kind: Namespace
metadata:
  name: ci
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dptp-controller-manager
  namespace: ci
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dptp-controller-manager
rules:
# appci
- apiGroups:
  - ci.openshift.io
  resources:
  - ephemeralclusters
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ci.openshift.io
  resources:
  - ephemeralclusters/status
  verbs:
  - update
- apiGroups:
  - prow.k8s.io
  resources:
  - prowjobs
  verbs:
  - "*"
# build01
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - watch
  - get
  - create
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dptp-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dptp-controller-manager
subjects:
- kind: ServiceAccount
  name: dptp-controller-manager
  namespace: ci
